name: Check that the code compiles

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: panda-arc

    steps:
      - name: Install git
        run: sudo apt-get -qq update -y && sudo apt-get -qq install git -y

      - uses: actions/checkout@v4 # Clones to $GITHUB_WORKSPACE. NOTE: this requires git > 2.18 (not on ubuntu 18.04 by default) to get .git directory and submodules
        with:
          fetch-depth: 0
          #submodules: 'true'

      # Instead of getting submodules with checkout, we can do it manually to control depth.
      # We don't want a full Linux history
      - name: Pull kernel source
        run: git submodule update --init --depth 1

      - name: Build Kernel
        run: ./build.sh
